packages:
    - 'infra-constructs/admiral-constructs'
    - 'infra-constructs/aos-ami-constructs'
    - 'infra-constructs/aos-opensearch-constructs'
    - 'infra-constructs/aos-internal-constructs'
    - 'infra-constructs/aos-cluster-constructs'
    - 'providers/opensearch/schemas'
    - 'providers/opensearch/s3-snapshot-repo'
    - 'providers/opensearch/snapshot-policy'
    - 'admiral/infrastructure'