packages:
    - 'admiral/api'
    - 'infra-constructs/admiral-constructs'
    - 'infra-constructs/aos-ami-constructs'
    - 'infra-constructs/aos-opensearch-constructs'
    - 'infra-constructs/aos-internal-constructs'
    - 'infra-constructs/aos-cluster-constructs'
    - 'infra-constructs/aos-domain-constructs'
    - 'infra-constructs/aos-product-constructs'
    - 'plugins/wing-opensearch'
    - 'providers/schemas'
    - 'providers/r53purchaser'
    - 'providers/fiefdom'
    - 'providers/opensearch/s3-snapshot-repo'
    - 'providers/opensearch/snapshot-policy'
    - 'admiral/infrastructure'
    - 'docs/library'
    - 'tools/ro-builder'
    - 'handlers/account-mail-processor'
    - 'handlers/ruleset-activator'
    - 'handlers/image-deployer'