// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	KeySize          *int    `json:",omitempty"`
	ExpirationDays   *int    `json:",omitempty"`
	RootCASecretId   *string `json:",omitempty"`
	CommonName       *string `json:",omitempty"`
	Tags             []Tag   `json:",omitempty"`
	AcmCertificateId *string `json:",omitempty"`
}

// Tag is autogenerated from the json schema
type Tag struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}
