// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ProjectName   *string           `json:",omitempty"`
	CliCommand    *string           `json:",omitempty"`
	RoleArn       *string           `json:",omitempty"`
	Hydration     *HydrationOptions `json:",omitempty"`
	InvocationId  *string           `json:",omitempty"`
	CommandOutput *string           `json:",omitempty"`
}

// HydrationOptions is autogenerated from the json schema
type HydrationOptions struct {
	SubstrateParamName    *string `json:",omitempty"`
	ControlPlaneParamName *string `json:",omitempty"`
	DataPlaneParamName    *string `json:",omitempty"`
}
