// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	KeySize              *int     `json:",omitempty"`
	Subject              *Subject `json:",omitempty"`
	ExpirationDays       *float64 `json:",omitempty"`
	PrivateKeyKmsKeyId   *string  `json:",omitempty"`
	PrivateKeySecretName *string  `json:",omitempty"`
	PublicCertificatePem *string  `json:",omitempty"`
	Serial               *string  `json:",omitempty"`
	PrivateKeySecretArn  *string  `json:",omitempty"`
}

// Subject is autogenerated from the json schema
type Subject struct {
	CommonName         *string `json:",omitempty"`
	Organization       *string `json:",omitempty"`
	OrganizationalUnit *string `json:",omitempty"`
	Country            *string `json:",omitempty"`
	State              *string `json:",omitempty"`
	City               *string `json:",omitempty"`
}
