searchendpoint: ""
searchcredentialsarn: ""
stage: beta
certificates:
    certificateauthoritysecretid: arn:aws:secretsmanager:us-west-2:609912790087:secret:/hp-search-beta-n528gsmwtn/maestro/rootCa-PrkkNt
    keysize: 2048
cloud:
    awsassumerolearn: ""
    awsprofile: hitchpin
    awsregion: us-west-2
cli:
    loglevel: Info
    logformat: text
    logdebuginformation: false
conf:
    eventbusname: hp-search-beta-n528gsmwtn-maestro
    eventloggroupname: "arn:aws:logs:us-west-2:609912790087:log-group:HpSearch-betaN528GSMWTNMaestroEvents:*"
    configbucket: hp-search-beta-n528gsmwtn-assets
    configprefix: ""
    clusternameparameterid: /hp-search-beta-n528gsmwtn/maestro/clusterName
    clustermodeparameterid: /hp-search-beta-n528gsmwtn/maestro/clusterMode
    clusteradminsecretid: arn:aws:secretsmanager:us-west-2:609912790087:secret:/hp-search-beta-n528gsmwtn/maestro/clusterAdmin-AXEIFI
discovery:
    serviceid: srv-ijohvepllmmmc5id
    servicename: ""
    namespacename: internal.hitchpin.com
