searchendpoint: ""
searchcredentialsarn: ""
stage: beta
certificates:
    certificateauthoritysecretid: arn:aws:secretsmanager:us-east-2:211125312321:secret:ControlPlaneRootCA5037C383-LqhpXT
    keysize: 2048
cloud:
    awsassumerolearn: ""
    awsprofile: hp-resource-providers
    awsregion: us-east-2
cli:
    loglevel: Info
    logformat: text
    logdebuginformation: false
conf:
    eventbusname: hpbetaabc123-maestro
    eventloggroupname: HpBetaabc123-MaestroEvents
    configbucket: hpbetaabc123-assets
    configprefix: config/
    clusternameparameterid: /HpBeta-abc123/maestro/clusterName
    clustermodeparameterid: /HpBeta-abc123/maestro/clusterMode
    clusteradminsecretid: arn:aws:secretsmanager:us-east-2:211125312321:secret:/HpBeta-abc123/maestro/clusterAdminPwd-LT8HBO
discovery:
    serviceid: srv-f2wapqpnvupantnr
    servicename: search-nodes
    namespacename: internal.hitchpin.com
